"use client";
export type FeatureKey="adaptacion"|"proyecto"|"orientacion"|"manual"|"privacidad"|"evaluacion";
export type CourseFeatureKey="adaptacion"|"proyecto"|"orientacion"|"evaluacion";
export type FeatureVisibility=Record<FeatureKey,boolean>;
export type CourseVisibility=Record<CourseFeatureKey,string[]>;
export const allCourses=["3 años de Infantil","4 años de Infantil","5 años de Infantil","1º de Primaria","2º de Primaria","3º de Primaria","4º de Primaria","5º de Primaria","6º de Primaria","1º de ESO","2º de ESO","3º de ESO","4º de ESO"];
export const defaultFeatureVisibility:FeatureVisibility={adaptacion:true,proyecto:true,orientacion:true,manual:true,privacidad:true,evaluacion:true};
export const defaultCourseVisibility:CourseVisibility={adaptacion:[...allCourses],proyecto:[...allCourses],orientacion:[...allCourses],evaluacion:[...allCourses]};
const options:[FeatureKey,string,string][]=[["evaluacion","Evaluación inicial","Pruebas, rúbricas, Excel e informe del grupo."],["adaptacion","Adaptaciones","PRA y adaptaciones curriculares significativas."],["proyecto","Proyectos","Proyectos interdisciplinares y adaptados."],["orientacion","Departamento de Orientación","Banco de recursos multinivel del centro."],["manual","Manual de uso","Ayuda sobre el funcionamiento."],["privacidad","Privacidad","Protección y tratamiento de datos."]];
const hasCourses=(key:FeatureKey):key is CourseFeatureKey=>["adaptacion","proyecto","orientacion","evaluacion"].includes(key);
export default function AdminVisibility({value,courses,busy,onToggle,onToggleCourse}:{value:FeatureVisibility;courses:CourseVisibility;busy:string;onToggle:(key:FeatureKey)=>void;onToggleCourse:(section:CourseFeatureKey,course:string)=>void}){return <details className="admin-feature-visibility"><summary><span><strong>Secciones visibles en la web</strong><small>Elige qué apartados y cursos aparecen en la plataforma.</small></span><b>Mostrar secciones</b></summary><header><span>{Object.values(value).filter(Boolean).length} de {options.length} visibles</span></header><div>{options.map(([key,title,description])=><article key={key} className="admin-visibility-item"><div><strong>{title}</strong><small>{description}</small>{hasCourses(key)&&<details className="admin-course-visibility"><summary>Cursos visibles ({courses[key].length} de {allCourses.length})</summary><div>{allCourses.map(course=><button key={course} type="button" className={courses[key].includes(course)?"course-on":"course-off"} disabled={busy===`${key}:${course}`} onClick={()=>onToggleCourse(key,course)}>{course}<span>{courses[key].includes(course)?"Visible":"Oculto"}</span></button>)}</div></details>}</div><button type="button" role="switch" aria-checked={value[key]} className={value[key]?"feature-on":"feature-off"} disabled={busy===key} onClick={()=>onToggle(key)}><i/><span>{busy===key?"Guardando…":value[key]?"Visible":"Oculta"}</span></button></article>)}</div><small className="admin-visibility-note">Administrador permanece siempre disponible.</small></details>}
